default: &default
  ynab_base_url: 'https://app.youneedabudget.com'
  base_url: 'https://yanab.herokuapp.com'
  redirect_uri: 'callbacks'
  ynab_client_id: <%= ENV.fetch('YNAB_CLIENT_ID') %>
  ynab_client_secret: <%= ENV.fetch('YNAB_CLIENT_SECRET') %>

development:
  <<: *default
  base_url: 'http://localhost:5000'
  ynab_access_token: <%= ENV.fetch('YNAB_PERSONAL_ACCESS_TOKEN') %>

production:
  <<: *default

