default: &default
  ynab_base_url: 'https://app.youneedabudget.com'
  base_url: 'https://ynad.herokuapp.com'
  redirect_uri: 'callbacks'
  ynab_client_id: <%= ENV.fetch('YNAB_CLIENT_ID') %>
  ynab_client_secret: <%= ENV.fetch('YNAB_CLIENT_SECRET') %>
  sendgrid_user_name: <%= ENV.fetch('YNAD_SENDGRID_USERNAME') %>
  sendgrid_password: <%= ENV.fetch('YNAD_SENDGRID_PASSWORD') %>
  personal_email: 'pradyumna2905@gmail.com'

development:
  <<: *default
  base_url: 'http://localhost:5000'
  ynab_access_token: <%= ENV['YNAB_PERSONAL_ACCESS_TOKEN'] %>

production:
  <<: *default

